"use client";

import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, ShoppingBag, Trash2, X } from "lucide-react";
import { useCartStore } from "@/store/cartStore";
import { formatCurrency } from "@/lib/utils";

export default function CartDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { items, removeItem, updateQuantity, getSubtotal } = useCartStore();
  if (!open) return null;
  return <div className="fixed inset-0 z-50" role="dialog" aria-modal="true"><button className="absolute inset-0 bg-black/45" onClick={onClose} aria-label="Close cart" /><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-[#f8f7f3] shadow-xl"><div className="flex h-16 items-center justify-between border-b border-black/10 px-5"><h2 className="font-display text-2xl">Your cart</h2><button onClick={onClose} className="grid h-10 w-10 place-items-center" aria-label="Close cart"><X /></button></div>{items.length === 0 ? <div className="grid flex-1 place-items-center px-6 text-center"><div><ShoppingBag className="mx-auto h-12 w-12 text-neutral-300" /><h3 className="mt-4 font-display text-2xl">Your cart is empty</h3><Link href="/shop" onClick={onClose} className="mt-5 inline-block bg-black px-5 py-3 text-sm font-bold uppercase text-white">Browse shop</Link></div></div> : <><div className="flex-1 space-y-4 overflow-y-auto p-5">{items.map((item) => <div key={`${item.productId}-${item.size}`} className="flex gap-3 border-b border-black/10 pb-4">{item.productImage && <div className="relative h-24 w-20 shrink-0 overflow-hidden bg-neutral-100"><Image src={item.productImage} alt="" fill className="object-cover" sizes="80px" /></div>}<div className="min-w-0 flex-1"><p className="font-semibold leading-tight">{item.productName}</p><p className="mt-1 text-xs text-neutral-500">Size {item.size}</p><p className="mt-2 text-sm font-bold">{formatCurrency(item.unitPrice * item.quantity)}</p><div className="mt-2 flex items-center gap-2"><button onClick={() => updateQuantity(item.productId, item.size, item.quantity - 1)} className="grid h-8 w-8 place-items-center border border-black/20" aria-label="Decrease quantity"><Minus className="h-3 w-3" /></button><span className="w-6 text-center text-sm">{item.quantity}</span><button onClick={() => updateQuantity(item.productId, item.size, item.quantity + 1)} className="grid h-8 w-8 place-items-center border border-black/20" aria-label="Increase quantity"><Plus className="h-3 w-3" /></button><button onClick={() => removeItem(item.productId, item.size)} className="ml-auto grid h-8 w-8 place-items-center text-red-700" aria-label="Remove item"><Trash2 className="h-4 w-4" /></button></div></div></div>)}</div><div className="border-t border-black/10 bg-white p-5"><div className="flex justify-between text-lg font-bold"><span>Subtotal</span><span>{formatCurrency(getSubtotal())}</span></div><p className="mt-1 text-xs text-neutral-500">Delivery is calculated at checkout.</p><Link href="/checkout" onClick={onClose} className="mt-5 block bg-[#b61f32] px-5 py-4 text-center text-sm font-bold uppercase text-white">Proceed to checkout</Link></div></>}</aside></div>;
}
