import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const CDN = "https://res.cloudinary.com/demo/image/upload";

async function main() {
  console.log("Seeding database...");

  // ─── Brands ───────────────────────────────────────────────────────────────
  const [himalayan, urban, heritage] = await Promise.all([
    prisma.brand.upsert({
      where: { id: "brand_himalayan" },
      update: {},
      create: {
        id: "brand_himalayan",
        name: "Himalayan Threads",
        logo: `${CDN}/himalayan-threads-logo.png`,
        commissionRate: 0.12,
        isVerified: true,
      },
    }),
    prisma.brand.upsert({
      where: { id: "brand_urban" },
      update: {},
      create: {
        id: "brand_urban",
        name: "Urban Nepal",
        logo: `${CDN}/urban-nepal-logo.png`,
        commissionRate: 0.10,
        isVerified: true,
      },
    }),
    prisma.brand.upsert({
      where: { id: "brand_heritage" },
      update: {},
      create: {
        id: "brand_heritage",
        name: "Heritage Weaves",
        logo: `${CDN}/heritage-weaves-logo.png`,
        commissionRate: 0.15,
        isVerified: false,
      },
    }),
  ]);
  console.log(`Brands: ${himalayan.name}, ${urban.name}, ${heritage.name}`);

  // ─── Products ─────────────────────────────────────────────────────────────
  const productData = [
    // ── Himalayan Threads – Womens ──────────────────────────────────────────
    {
      id: "prod_kurta_white",
      name: "Classic White Kurta",
      slug: "classic-kurta-white",
      brandId: himalayan.id,
      price: 1499,
      category: "tops",
      garmentType: "tops",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["HOURGLASS", "RECTANGLE", "PEAR"],
      images: [`${CDN}/kurta-white-front.jpg`, `${CDN}/kurta-white-back.jpg`],
      description: "A timeless white cotton kurta, perfect for everyday wear.",
    },
    {
      id: "prod_salwar_blue",
      name: "Floral Blue Salwar Suit",
      slug: "floral-salwar-blue",
      brandId: himalayan.id,
      price: 2799,
      category: "sets",
      garmentType: "sets",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["S", "M", "L", "XL"],
      suitableBodyTypes: ["PEAR", "HOURGLASS", "APPLE"],
      images: [`${CDN}/salwar-blue-front.jpg`],
      description: "Elegant floral print salwar suit in calming blue tones.",
    },
    {
      id: "prod_dupatta_red",
      name: "Embroidered Red Dupatta",
      slug: "embroidered-dupatta-red",
      brandId: himalayan.id,
      price: 799,
      category: "accessories",
      garmentType: "accessories",
      gender: "unisex",
      isTryonEnabled: false,
      sizes: ["ONE_SIZE"],
      suitableBodyTypes: ["HOURGLASS", "PEAR", "APPLE", "RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/dupatta-red.jpg`],
      description: "Hand-embroidered dupatta with traditional Nepali motifs.",
    },
    {
      id: "prod_wrap_dress_green",
      name: "Wrap Dress Floral Green",
      slug: "wrap-dress-floral-green",
      brandId: himalayan.id,
      price: 3299,
      category: "dresses",
      garmentType: "dresses",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["HOURGLASS", "PEAR"],
      images: [`${CDN}/wrap-dress-green.jpg`],
      description: "Flattering wrap-style dress with a vibrant floral print.",
    },
    {
      id: "prod_aline_maxi_navy",
      name: "A-Line Maxi Dress Navy",
      slug: "aline-maxi-dress-navy",
      brandId: himalayan.id,
      price: 3899,
      category: "dresses",
      garmentType: "dresses",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L"],
      suitableBodyTypes: ["PEAR", "RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/aline-maxi-navy.jpg`],
      description: "Elegant A-line maxi dress, perfect for evening events.",
    },
    {
      id: "prod_high_waist_skirt",
      name: "High Waist Floral Wrap Skirt",
      slug: "high-waist-floral-wrap-skirt",
      brandId: himalayan.id,
      price: 1799,
      category: "bottoms",
      garmentType: "bottoms",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["PEAR", "APPLE", "HOURGLASS"],
      images: [`${CDN}/high-waist-floral-skirt.jpg`],
      description: "Feminine wrap skirt with a flattering high waist cut.",
    },
    {
      id: "prod_palazzo_wide",
      name: "Wide Leg Palazzo Pants",
      slug: "wide-leg-palazzo-pants",
      brandId: himalayan.id,
      price: 2099,
      category: "bottoms",
      garmentType: "bottoms",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      suitableBodyTypes: ["INVERTED_TRIANGLE", "APPLE", "RECTANGLE"],
      images: [`${CDN}/palazzo-wide-leg.jpg`],
      description: "Flowy wide-leg palazzo pants for a comfortable, elegant look.",
    },
    {
      id: "prod_festive_lengha",
      name: "Festive Lengha Set",
      slug: "festive-lengha-set",
      brandId: himalayan.id,
      price: 6999,
      category: "sets",
      garmentType: "sets",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["S", "M", "L", "XL"],
      suitableBodyTypes: ["HOURGLASS", "PEAR", "RECTANGLE"],
      images: [`${CDN}/lengha-festive.jpg`],
      description: "Stunning festive lengha set with intricate embroidery.",
    },
    {
      id: "prod_ruffled_blouse_coral",
      name: "Ruffled Blouse Coral",
      slug: "ruffled-blouse-coral",
      brandId: himalayan.id,
      price: 1299,
      category: "tops",
      garmentType: "tops",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/ruffled-blouse-coral.jpg`],
      description: "Playful ruffled blouse that adds volume and femininity.",
    },
    {
      id: "prod_vneck_fit_dress",
      name: "V-Neck Fitted Dress",
      slug: "vneck-fitted-dress",
      brandId: himalayan.id,
      price: 2599,
      category: "dresses",
      garmentType: "dresses",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["HOURGLASS", "RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/vneck-fitted-dress.jpg`],
      description: "Sleek V-neck dress that flatters an athletic figure.",
    },
    {
      id: "prod_bell_jeans",
      name: "Bell Bottom Jeans",
      slug: "bell-bottom-jeans",
      brandId: himalayan.id,
      price: 2399,
      category: "bottoms",
      garmentType: "bottoms",
      gender: "womens",
      isTryonEnabled: false,
      sizes: ["26", "28", "30", "32"],
      suitableBodyTypes: ["INVERTED_TRIANGLE", "RECTANGLE"],
      images: [`${CDN}/bell-bottom-jeans.jpg`],
      description: "Retro-inspired bell bottom jeans, flattering for slimmer hips.",
    },
    {
      id: "prod_embellished_suit",
      name: "Embellished Salwar Kameez",
      slug: "embellished-salwar-kameez",
      brandId: himalayan.id,
      price: 4599,
      category: "sets",
      garmentType: "sets",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["S", "M", "L", "XL", "XXL"],
      suitableBodyTypes: ["APPLE", "PEAR", "RECTANGLE"],
      images: [`${CDN}/embellished-salwar.jpg`],
      description: "Richly embellished salwar kameez for special occasions.",
    },
    // ── Urban Nepal – Mens ───────────────────────────────────────────────────
    {
      id: "prod_chinos_beige",
      name: "Slim Fit Beige Chinos",
      slug: "slim-fit-chinos-beige",
      brandId: urban.id,
      price: 1999,
      category: "bottoms",
      garmentType: "bottoms",
      gender: "mens",
      isTryonEnabled: false,
      sizes: ["28", "30", "32", "34", "36"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/chinos-beige.jpg`],
      description: "Versatile slim fit chinos in a neutral beige.",
    },
    {
      id: "prod_shirt_navy",
      name: "Linen Navy Shirt",
      slug: "linen-shirt-navy",
      brandId: urban.id,
      price: 1699,
      category: "tops",
      garmentType: "tops",
      gender: "mens",
      isTryonEnabled: true,
      sizes: ["S", "M", "L", "XL", "XXL"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE", "APPLE"],
      images: [`${CDN}/linen-shirt-navy.jpg`],
      description: "Breathable linen shirt in classic navy, ideal for warm days.",
    },
    {
      id: "prod_oxford_shirt",
      name: "Classic Oxford Shirt",
      slug: "classic-oxford-shirt",
      brandId: urban.id,
      price: 1849,
      category: "tops",
      garmentType: "tops",
      gender: "mens",
      isTryonEnabled: true,
      sizes: ["S", "M", "L", "XL", "XXL"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/oxford-shirt-white.jpg`],
      description: "Crisp cotton oxford shirt, a wardrobe essential.",
    },
    {
      id: "prod_blazer_grey",
      name: "Formal Blazer Grey",
      slug: "formal-blazer-grey",
      brandId: urban.id,
      price: 4999,
      category: "outerwear",
      garmentType: "outerwear",
      gender: "mens",
      isTryonEnabled: false,
      sizes: ["S", "M", "L", "XL"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE", "APPLE"],
      images: [`${CDN}/blazer-grey-formal.jpg`],
      description: "Tailored grey blazer for a sharp, professional look.",
    },
    {
      id: "prod_straight_trousers",
      name: "Straight Leg Black Trousers",
      slug: "straight-leg-black-trousers",
      brandId: urban.id,
      price: 2199,
      category: "bottoms",
      garmentType: "bottoms",
      gender: "unisex",
      isTryonEnabled: false,
      sizes: ["28", "30", "32", "34", "36"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE", "PEAR"],
      images: [`${CDN}/straight-trousers-black.jpg`],
      description: "Timeless straight-leg trousers in versatile black.",
    },
    {
      id: "prod_tshirt_cotton",
      name: "Cotton Casual T-Shirt",
      slug: "cotton-casual-tshirt",
      brandId: urban.id,
      price: 699,
      category: "tops",
      garmentType: "tops",
      gender: "unisex",
      isTryonEnabled: false,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      suitableBodyTypes: ["HOURGLASS", "PEAR", "APPLE", "RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/cotton-tshirt-white.jpg`],
      description: "Soft 100% cotton t-shirt available in multiple colours.",
    },
    {
      id: "prod_crop_top",
      name: "Crop Top White Cotton",
      slug: "crop-top-white-cotton",
      brandId: urban.id,
      price: 899,
      category: "tops",
      garmentType: "tops",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L"],
      suitableBodyTypes: ["RECTANGLE", "INVERTED_TRIANGLE", "HOURGLASS"],
      images: [`${CDN}/crop-top-white.jpg`],
      description: "Chic white crop top, pairs well with high-waist bottoms.",
    },
    {
      id: "prod_denim_jacket",
      name: "Oversized Denim Jacket",
      slug: "oversized-denim-jacket",
      brandId: urban.id,
      price: 3499,
      category: "outerwear",
      garmentType: "outerwear",
      gender: "unisex",
      isTryonEnabled: false,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["APPLE", "RECTANGLE", "PEAR"],
      images: [`${CDN}/denim-jacket-oversized.jpg`],
      description: "Relaxed oversized denim jacket for layered looks.",
    },
    // ── Heritage Weaves – Traditional & Artisan ──────────────────────────────
    {
      id: "prod_silk_kurta_gold",
      name: "Embroidered Silk Kurta Gold",
      slug: "embroidered-silk-kurta-gold",
      brandId: heritage.id,
      price: 5499,
      category: "tops",
      garmentType: "tops",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["S", "M", "L", "XL"],
      suitableBodyTypes: ["HOURGLASS", "RECTANGLE", "PEAR"],
      images: [`${CDN}/silk-kurta-gold.jpg`],
      description: "Hand-embroidered silk kurta with golden threadwork.",
    },
    {
      id: "prod_striped_coord",
      name: "Striped Co-ord Set",
      slug: "striped-coord-set",
      brandId: heritage.id,
      price: 3199,
      category: "sets",
      garmentType: "sets",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["RECTANGLE", "PEAR", "APPLE"],
      images: [`${CDN}/striped-coord-set.jpg`],
      description: "Modern co-ord set with bold stripes for a polished look.",
    },
    {
      id: "prod_dhaka_topi",
      name: "Traditional Dhaka Topi",
      slug: "traditional-dhaka-topi",
      brandId: heritage.id,
      price: 599,
      category: "accessories",
      garmentType: "accessories",
      gender: "mens",
      isTryonEnabled: false,
      sizes: ["ONE_SIZE"],
      suitableBodyTypes: ["HOURGLASS", "PEAR", "APPLE", "RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/dhaka-topi-traditional.jpg`],
      description: "Authentic Dhaka fabric topi — a symbol of Nepali heritage.",
    },
    {
      id: "prod_flared_midi",
      name: "Flared Midi Skirt",
      slug: "flared-midi-skirt",
      brandId: heritage.id,
      price: 1899,
      category: "bottoms",
      garmentType: "bottoms",
      gender: "womens",
      isTryonEnabled: true,
      sizes: ["XS", "S", "M", "L", "XL"],
      suitableBodyTypes: ["INVERTED_TRIANGLE", "RECTANGLE", "APPLE"],
      images: [`${CDN}/flared-midi-skirt.jpg`],
      description: "Graceful flared midi skirt that balances broader shoulders.",
    },
    {
      id: "prod_pashmina_shawl",
      name: "Pashmina Shawl Multicolor",
      slug: "pashmina-shawl-multicolor",
      brandId: heritage.id,
      price: 2499,
      category: "accessories",
      garmentType: "accessories",
      gender: "unisex",
      isTryonEnabled: false,
      sizes: ["ONE_SIZE"],
      suitableBodyTypes: ["HOURGLASS", "PEAR", "APPLE", "RECTANGLE", "INVERTED_TRIANGLE"],
      images: [`${CDN}/pashmina-shawl.jpg`],
      description: "Luxurious hand-woven pashmina shawl in vibrant colours.",
    },
  ];

  const products = await Promise.all(
    productData.map((p) =>
      prisma.product.upsert({
        where: { slug: p.slug },
        update: {},
        create: p,
      })
    )
  );
  console.log(`Products: ${products.length} seeded`);

  // ─── Size Charts ──────────────────────────────────────────────────────────
  const sizeChartData = [
    // Himalayan Threads
    { brandId: himalayan.id, size: "XS", bustMin: 78, bustMax: 82, waistMin: 60, waistMax: 64, hipsMin: 84, hipsMax: 88, sortOrder: 0 },
    { brandId: himalayan.id, size: "S",  bustMin: 82, bustMax: 86, waistMin: 64, waistMax: 68, hipsMin: 88, hipsMax: 92, sortOrder: 1 },
    { brandId: himalayan.id, size: "M",  bustMin: 86, bustMax: 92, waistMin: 68, waistMax: 74, hipsMin: 92, hipsMax: 98, sortOrder: 2 },
    { brandId: himalayan.id, size: "L",  bustMin: 92, bustMax: 100, waistMin: 74, waistMax: 82, hipsMin: 98, hipsMax: 106, sortOrder: 3 },
    { brandId: himalayan.id, size: "XL", bustMin: 100, bustMax: 108, waistMin: 82, waistMax: 90, hipsMin: 106, hipsMax: 114, sortOrder: 4 },
    { brandId: himalayan.id, size: "XXL", bustMin: 108, bustMax: 118, waistMin: 90, waistMax: 100, hipsMin: 114, hipsMax: 124, sortOrder: 5 },
    // Urban Nepal
    { brandId: urban.id, size: "XS", bustMin: 76, bustMax: 82, waistMin: 58, waistMax: 64, hipsMin: 82, hipsMax: 88, sortOrder: 0 },
    { brandId: urban.id, size: "S",  bustMin: 82, bustMax: 88, waistMin: 64, waistMax: 70, hipsMin: 88, hipsMax: 94, sortOrder: 1 },
    { brandId: urban.id, size: "M",  bustMin: 88, bustMax: 94, waistMin: 70, waistMax: 76, hipsMin: 94, hipsMax: 100, sortOrder: 2 },
    { brandId: urban.id, size: "L",  bustMin: 94, bustMax: 102, waistMin: 76, waistMax: 84, hipsMin: 100, hipsMax: 108, sortOrder: 3 },
    { brandId: urban.id, size: "XL", bustMin: 102, bustMax: 110, waistMin: 84, waistMax: 92, hipsMin: 108, hipsMax: 116, sortOrder: 4 },
    { brandId: urban.id, size: "XXL", bustMin: 110, bustMax: 120, waistMin: 92, waistMax: 102, hipsMin: 116, hipsMax: 126, sortOrder: 5 },
    // Heritage Weaves
    { brandId: heritage.id, size: "XS", bustMin: 78, bustMax: 84, waistMin: 60, waistMax: 66, hipsMin: 84, hipsMax: 90, sortOrder: 0 },
    { brandId: heritage.id, size: "S",  bustMin: 84, bustMax: 90, waistMin: 66, waistMax: 72, hipsMin: 90, hipsMax: 96, sortOrder: 1 },
    { brandId: heritage.id, size: "M",  bustMin: 90, bustMax: 96, waistMin: 72, waistMax: 78, hipsMin: 96, hipsMax: 102, sortOrder: 2 },
    { brandId: heritage.id, size: "L",  bustMin: 96, bustMax: 104, waistMin: 78, waistMax: 86, hipsMin: 102, hipsMax: 110, sortOrder: 3 },
    { brandId: heritage.id, size: "XL", bustMin: 104, bustMax: 112, waistMin: 86, waistMax: 94, hipsMin: 110, hipsMax: 118, sortOrder: 4 },
  ];

  for (const sc of sizeChartData) {
    await prisma.sizeChart.upsert({
      where: {
        brandId_size: { brandId: sc.brandId, size: sc.size },
      },
      update: sc,
      create: sc,
    });
  }
  console.log(`SizeCharts: ${sizeChartData.length} seeded`);

  // ─── Test user ────────────────────────────────────────────────────────────
  const user = await prisma.user.upsert({
    where: { email: "test@vtryon.com" },
    update: {},
    create: {
      id: "user_test_001",
      email: "test@vtryon.com",
      name: "Test User",
      supabaseId: "supabase_test_001",
      bodyProfile: {
        create: {
          height: 165,
          weight: 60,
          bust: 86,
          waist: 68,
          hips: 92,
          shoulders: 38,
          bodyType: "HOURGLASS",
        },
      },
      styleProfile: {
        create: {
          preferredStyles: ["casual", "traditional", "smart-casual"],
          occasions: ["daily", "festivals", "office"],
          colorPalette: ["navy", "white", "maroon", "beige"],
        },
      },
    },
  });
  console.log(`User: ${user.email}`);
  console.log("Seeding complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
